[package]
name = "dobbydb-parser"
version = {workspace = true}
edition = {workspace = true}

[[bin]]
name = "dobbydb-parser"
path = "src/main.rs"

[dependencies]
datafusion = {workspace = true}
sqlparser = {workspace = true}
#datafusion-sql = {workspace = true}